Update documentation with information on creation and updating a granule via API
nasa/cumulus-api pull request #310
Opened 2021-09-09 16:02 UTC by flamingbear

2021-09-10 13:52 UTC, jennyhliu commented on content/granules.md
> +| `beginningDateTime` | `string`| `no` | The time when the granule's temporal coverage begins,
Can you remove the ending `,`?
```suggestion
| `beginningDateTime` | `string`| `no` | The time when the granule's temporal coverage begins |
```

2021-09-10 14:43 UTC, jennyhliu commented on content/granules.md
> +$ curl --request POST https://example.com/granules/granuleId.A19990103.006.1000 \
```suggestion
$ curl --request PUT https://example.com/granules/granuleId.A19990103.006.1000 \
```

2021-09-10 14:46 UTC, jennyhliu commented on content/granules.md
> +  "status": "running",
```suggestion
  "status": "running"
```

2021-09-10 15:26 UTC, jennyhliu requested changes

2021-09-10 15:26 UTC, jennyhliu commented on content/granules.md
> +  "status": "running",
I tested on my stack, and the `files` and `status` are not updated due to:
https://github.com/nasa/cumulus/blob/master/packages/api/models/granules.js#L604-L605
I suggested to change the `status` to `running` in create request, and `completed` in update request.

2021-09-10 15:26 UTC, jennyhliu commented on content/granules.md
> +  "status": "running",
<img width="1094" alt="Screen Shot 2021-09-10 at 11 10 36 AM" src="https://user-images.githubusercontent.com/34660846/132878005-f00eb99a-a56b-41ca-a659-5bec8c63f445.png">
The `Filename` column in dashboard individual granule page is empty, so suggest to add `fileName` to both create and update request examples

2021-09-10 15:35 UTC, jennyhliu commented on content/granules.md
> +  "granuleId": "granuleId.A19990103.006.1000",
I also suggest to add `collectionId` since `granuleId+collectionId` is unique in RDS schema

2021-09-10 16:18 UTC, jennyhliu commented on content/granules.md
> +#### Example request
I suggest the granule in the example request has all the possible fields, so the user gets an idea what the fields look like

2021-09-13 17:09 UTC, flamingbear commented on content/granules.md
> +  "granuleId": "granuleId.A19990103.006.1000",
53fbd37

2021-09-13 17:09 UTC, flamingbear commented on content/granules.md
> +#### Example request
53fbd37

2021-09-13 17:41 UTC, flamingbear commented
@jennyhliu I think this is ready for re-review.

2021-09-13 19:25 UTC, jennyhliu approved these changes
👍

2021-09-13 19:27 UTC, merged