CUMULUS-3856 Update cumulus-api document
nasa/cumulus-api pull request #360
Opened 2024-12-18 16:18 UTC by tclark-innovim

Addresses issues in [CUMULUS-3856](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3856)

2025-01-18 00:56 UTC, jennyhliu requested changes
In the response of the list endpoints, meta.table is the actual table names, please update  the example responses, e.g. `table: granules`
https://github.com/nasa/cumulus/blob/feature/es-phase-2/packages/db/src/tables.ts

2025-01-18 00:56 UTC, jennyhliu commented on content/executions.md
Please make clear the default value for these two parameters.  These are for the List endpoints, and don't get endpoint for individual record.

2025-01-18 00:56 UTC, jennyhliu commented on content/executions.md
> +If the query string parameters include a value of `true` for `includeFullRecord`, any associated async operations and parent execution will be included in the executions's return value.
includeFullRecord is for search records, no update for getting individual record, this should be removed.

2025-01-18 00:56 UTC, jennyhliu commented on content/granules.md
> +$ curl https://example.com/granules --header 'Authorization: Bearer ReplaceWithTheToken'
```suggestion
$ curl https://example.com/granules?includeFullRecord=true --header 'Authorization: Bearer ReplaceWithTheToken'
```

2025-01-18 00:56 UTC, jennyhliu commented on content/granules.md
> +$ curl https://example.com/granules --header 'Authorization: Bearer ReplaceWithTheToken'
When includeFullRecord is not set to true, the response won't have files and execution information.

2025-01-18 00:56 UTC, jennyhliu commented on content/granules.md
> +If the query string parameters include a value of `true` for `includeFullRecord`, any associated files and executions will be included in the granule's return value.
includeFullRecord for for list endpoints. This update can be removed.

2025-01-21 14:09 UTC, tclark-innovim commented
@jennyhliu Thanks for the feedback, I will review and make code updates

2025-01-27 17:20 UTC, jennyhliu commented on content/intro.md
> +| `limit={number}` | Number of records to be returned by the API call; default is `1`, maximum is `100`. A value of `null` will return all records. |
```suggestion
| `limit={number}` | Number of records to be returned by the API call; default is `1`, maximum is `100`. A value of `0` will return all records. |
```

2025-01-27 19:17 UTC, charleshuang80 commented
Sorry to jump into this late, I wanted to look into this and provide some feedback but was focused on my other ticket. My one suggestion for now is to update the description for prefix and infix in the table in the intro. Because we're switching from ES to PG style queries, these queries don't quite have the same functionality. And if you do a search for infix and prefix in the core code for the feature branch, we are generally just using `whereLike` on specific fields. So I don't think all the fields listed are being used, and `startsWith` no longer applies.
There may be one other suggestion I have but I'll need to look through some notes to try and remember if it is something that needs to be addressed.

2025-01-28 17:53 UTC, tclark-innovim commented on content/executions.md
I added documentation for the default values of `includeFullRecord` and `estimateTableRowCount`. I removed documentation for the get endpoint for the individual record.

2025-01-28 17:54 UTC, tclark-innovim commented on content/executions.md
> +If the query string parameters include a value of `true` for `includeFullRecord`, any associated async operations and parent execution will be included in the executions's return value.
I have removed this.

2025-01-28 17:54 UTC, tclark-innovim commented on content/granules.md
> +$ curl https://example.com/granules --header 'Authorization: Bearer ReplaceWithTheToken'
I added `?includeFullRecord=true` to the example request.

2025-01-28 17:55 UTC, tclark-innovim commented on content/granules.md
> +If the query string parameters include a value of `true` for `includeFullRecord`, any associated files and executions will be included in the granule's return value.
I have removed this.

2025-01-28 17:55 UTC, tclark-innovim commented
> one I think you might have missed:
> 
> https://nasa.github.io/cumulus-api/unreleased/#migration-counts

I removed the Migration Counts section.

2025-01-28 17:56 UTC, tclark-innovim commented on content/intro.md
> +| `limit={number}` | Number of records to be returned by the API call; default is `1`, maximum is `100`. A value of `null` will return all records. |
I changed the `null` to `0`.

2025-01-28 18:29 UTC, tclark-innovim commented
> Sorry to jump into this late, I wanted to look into this and provide some feedback but was focused on my other ticket. My one suggestion for now is to update the description for prefix and infix in the table in the intro. Because we're switching from ES to PG style queries, these queries don't quite have the same functionality. And if you do a search for infix and prefix in the core code for the feature branch, we are generally just using `whereLike` on specific fields. So I don't think all the fields listed are being used, and `startsWith` no longer applies. There may be one other suggestion I have but I'll need to look through some notes to try and remember if it is something that needs to be addressed.

@charleshuang80 I am looking through the code in the `feature/es-phase-2` branch, and I see that infix and prefix are still being used in the queries. I checked these object types and fields, and they are still being searched. Let me know if you see something different.

Example: 
![image](https://github.com/user-attachments/assets/27c0ded4-5b71-4453-9007-045136970ddd)

2025-01-28 18:31 UTC, tclark-innovim commented
@jennyhliu @Nnaga1 @charleshuang80 I have implemented the feedback that I have received on this PR. Can you review again? Thanks!

2025-01-28 18:37 UTC, jennyhliu approved these changes
Nice work!

2025-01-28 21:07 UTC, charleshuang80 commented on content/intro.md
> -| `prefix={value}` | `startsWith` search of the `granuleId`, `status`, `pdrName`, `name`, `error`, `id` and `msg` fields |
Thanks for making these changes. Overall it looks good and I think is clearer.
My one small nit here is that since the prefix queries in our code are using `whereLike` instead of `startsWith` the description seems misleading. While a query will match the beginning, it will also match other sections, so `includes` seems more accurate. But that means the `prefix` usage is inexact, though we are keeping it the functionality and not break existing things using the query term.
I don't know what should be done here, but it does feel a bit weird to be sort of misleading, and I guess I'm wondering what you or others think.

2025-01-29 16:34 UTC, tclark-innovim commented on content/intro.md
> -| `prefix={value}` | `startsWith` search of the `granuleId`, `status`, `pdrName`, `name`, `error`, `id` and `msg` fields |
@charleshuang80 In the code snippet below, when `prefix` is provided, the database operator `like` is used, but there is no percent sign `%` to the left of the prefix value, only to the right of it. That means the database should only return records that have values **start with** the prefix value. 

![image](https://github.com/user-attachments/assets/7b8b38a8-6384-4e50-aed6-909c2a33cd04)

2025-01-29 16:46 UTC, tclark-innovim commented on content/executions.md
> +
I have removed the addition, so there is no net change. Thanks

2025-01-29 18:12 UTC, charleshuang80 approved these changes

2025-01-30 16:59 UTC, merged